name = "coap_spark"
description = "CoAP implementation formally verified with SPARK/Ada"
version = "0.1.0-dev"

authors = ["Manuel Gomez"]
maintainers = ["Manuel Gomez <mgrojo@gmail.com>"]
maintainers-logins = ["mgrojo"]
licenses = "MIT"
website = "https://github.com/mgrojo/coap_spark"
tags = ["spark", "coap", "iot", "protocol"]

[[depends-on]]
gnatprove = "^14.1.1"

[build-switches]
"*".style_checks = ["-gnatyC"]
