RFLX_HOME := tools/RecordFlux/
RFLX := $(RFLX_HOME)/.venv/bin/rflx
SPECS = $(wildcard specs/*.rflx)
GNATPROVE := gnatprove

GENERATED = generated/$(SPECS:.rflx=.ads)

all: generate
.PHONY: all

# Beware that for CoAP, the only useful type generated by
# its IANA registry is the CoAP Option Code, and we are
# copying it to the manually written coap.rflx, instead of
# including the generated one.
convert_iana: spec/iana_registry/core-parameters.xml
	$(RFLX) convert iana -d spec $<
.PHONY: convert_iana

generate: $(GENERATED)
.PHONY: generate

$(GENERATED): $(SPECS)
	@mkdir -p $(dir $@)
	@$(RFLX) generate -d $(dir $@) $<
	@$(RFLX) graph -d $(dir $@) $<

test:
	$(MAKE) -C tests test
.PHONY: test

clean:
	rm -r $(dir $(GENERATED))
.PHONY: clean

prove: $(GENERATED)
	$(GNATPROVE) -Pcoap_spark.gpr
.PHONY: prove
