------------------------------------------------------------------------------
--                                                                          --
--               Generated by RecordFlux 0.25.0 on 2025-06-28               --
--                                                                          --
--                     Copyright (C) 2018-2025 AdaCore                      --
--                                                                          --
--         SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception          --
--                                                                          --
------------------------------------------------------------------------------

package body RFLX.CoAP_Server.Main_Loop
  with SPARK_Mode
is

   procedure Get_Response
     (State       : in out RFLX.CoAP_Server.Main_Loop_Environment.State;
      Request     : RFLX.CoAP_Server.Definite_Message.Structure;
      RFLX_Result : out RFLX.CoAP_Server.Application_Response.Structure)
   is
   begin
      null;
   end Get_Response;

   procedure Get_Error_Options_And_Payload
     (State       : in out RFLX.CoAP_Server.Main_Loop_Environment.State;
      RFLX_Result : out RFLX.CoAP_Server.Options_And_Payload_Data.Structure) is
   begin
      null;
   end Get_Error_Options_And_Payload;

end RFLX.CoAP_Server.Main_Loop;
