name: GNATprove

on:
  push:
    paths:
      - '.github/workflows/prove.yml'
      - 'src/**'
      - 'client/src/**'
      - 'server/src/**'
      - 'alire.toml'
      - 'client/alire.toml'
      - 'server/alire.toml'
      - 'coap_spark.gpr'
      - 'client/coap_client.gpr'
      - 'server/coap_server.gpr'
      - 'libs/wolfssl'
  pull_request:        # - A pull-request is opened or updated.
    paths:
      - '.github/workflows/prove.yml'
      - 'src/**'
      - 'client/src/**'
      - 'server/src/**'
      - 'alire.toml'
      - 'client/alire.toml'
      - 'server/alire.toml'
      - 'coap_spark.gpr'
      - 'client/coap_client.gpr'
      - 'server/coap_server.gpr'
      - 'libs/wolfssl'
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  gnatprove:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [client, server]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true' # Also checkout recursively the submodules

    # Install and setup Alire package manager
    - uses: alire-project/setup-alire@v2
      with:
        version: 2.1.0 # Remove this option to use the default (latest stable release)

    - name: Run GNATprove (${{ matrix.target }})
      working-directory: ${{ matrix.target }}
      run: |
        set -e
        alr build --stop-after=generation
        alr gnatprove -j0 --level=4
        {
          echo '```'
          echo "# GNATprove summary for ${matrix_target:-${{ matrix.target }}}"
          head -23 obj/development/gnatprove/gnatprove.out || echo "No summary available"
          echo '```'
        } >> $GITHUB_STEP_SUMMARY



